# Railway configuration for monorepo with Dockerfiles

# Frontend service
[frontend]
name = "paxform-frontend"
root = "frontend"

[frontend.build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[frontend.deploy]
startCommand = "/usr/sbin/nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 30

# Backend service
[backend]
name = "paxform-backend"
root = "backend"

[backend.build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[backend.deploy]
startCommand = "sh /var/www/start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

# Environment variables
[environments]
  [environments.production]
    NODE_ENV = "production"
    VITE_API_URL = "https://paxform-assessment-url.railway.app"
    PORT = 80
    
    # Database configuration
    DB_CONNECTION = "mysql"
    DB_HOST = "${RAILWAY_MYSQLHOST}"
    DB_PORT = "${RAILWAY_MYSQLPORT}"
    DB_DATABASE = "${RAILWAY_MYSQLDATABASE}"
    DB_USERNAME = "${RAILWAY_MYSQLUSER}"
    DB_PASSWORD = "${RAILWAY_MYSQLPASSWORD}"
