# This is a monorepo configuration for Railway
# Each service will be built and deployed separately

# Frontend service (React)
[frontend]
name = "paxform-frontend"
root = "frontend"

# Use Nixpacks to build the frontend
[frontend.build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build"
  startCommand = "npx serve -s build -l $PORT"

[frontend.deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 30

# Backend service (Laravel)
[backend]
name = "paxform-backend"
root = "backend"

# Use Nixpacks to build the backend
[backend.build]
  builder = "nixpacks"
  buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"
  startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"

[backend.deploy]
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30

# Environment variables
[environments]
  [environments.production]
    NODE_ENV = "production"
    VITE_API_URL = "https://paxform-assessment-url.railway.app"
    PORT = 80
    
    # Database configuration
    DB_CONNECTION = "mysql"
    DB_HOST = "${RAILWAY_MYSQLHOST}"
    DB_PORT = "${RAILWAY_MYSQLPORT}"
    DB_DATABASE = "${RAILWAY_MYSQLDATABASE}"
    DB_USERNAME = "${RAILWAY_MYSQLUSER}"
    DB_PASSWORD = "${RAILWAY_MYSQLPASSWORD}"
