[build]
  builder = "NIXPACKS"

# Frontend service
[frontend]
name = "paxform-frontend"
root = "frontend"

[frontend.build]
builder = "NIXPACKS"

# Tell Nixpacks how to build the frontend
[frontend.build.nixpacks]
  [frontend.build.nixpacks.phases.setup]
  nixPkgs = ["nodejs"]
  
  [frontend.build.nixpacks.phases.install]
  cmds = ["npm ci"]
  
  [frontend.build.nixpacks.phases.build]
  cmds = ["npm run build"]
  
  [frontend.build.nixpacks.start]
  cmd = "npx serve --single --listen $PORT build"

[frontend.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30

# Backend service
[backend]
name = "paxform-backend"
root = "backend"

[backend.build]
builder = "NIXPACKS"

# Tell Nixpacks how to build the backend
[backend.build.nixpacks]
  [backend.build.nixpacks.phases.setup]
  nixPkgs = ["php82", "php82Extensions.composer", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.gd"]
  
  [backend.build.nixpacks.phases.install]
  cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
  ]
  
  [backend.build.nixpacks.start]
  cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[backend.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30

# Environment variables
[environments]
  [environments.production]
    NODE_ENV = "production"
    VITE_API_URL = "https://paxform-assessment-url.railway.app"
    PORT = 80
    
    # Database configuration
    DB_CONNECTION = "mysql"
    DB_HOST = "${RAILWAY_MYSQLHOST}"
    DB_PORT = "${RAILWAY_MYSQLPORT}"
    DB_DATABASE = "${RAILWAY_MYSQLDATABASE}"
    DB_USERNAME = "${RAILWAY_MYSQLUSER}"
    DB_PASSWORD = "${RAILWAY_MYSQLPASSWORD}"
