# Root configuration (not used directly by services)
[build]
  builder = "NIXPACKS"

# Frontend service
[frontend]
name = "paxform-frontend"

[frontend.build]
  builder = "DOCKERFILE"
  dockerfilePath = "frontend/Dockerfile"

[frontend.deploy]
  startCommand = "/usr/sbin/nginx -g 'daemon off;'"
  healthcheckPath = "/health"
  healthcheckTimeout = 30

# Backend service
[backend]
name = "paxform-backend"

[backend.build]
  builder = "DOCKERFILE"
  context = "."  # Set context to project root
  dockerfilePath = "backend/Dockerfile"  # Path to Dockerfile from project root
  healthcheckTimeout = 30

# Environment variables
[environments]
  [environments.production]
    # Frontend variables
    NODE_ENV = "production"
    VITE_API_URL = "/api"  # Relative path since frontend and backend are on the same domain
    PORT = "80"
    
    # Backend variables
    APP_ENV = "production"
    APP_DEBUG = "false"
    APP_URL = ""  # Will be set by Railway
    
    # Database configuration (provided by Railway)
    DB_CONNECTION = "mysql"
    DB_HOST = "${RAILWAY_MYSQLHOST}"
    DB_PORT = "${RAILWAY_MYSQLPORT}"
    DB_DATABASE = "${RAILWAY_MYSQLDATABASE}"
    DB_USERNAME = "${RAILWAY_MYSQLUSER}"
    DB_PASSWORD = "${RAILWAY_MYSQLPASSWORD}"
