# Railway configuration file
[build]
  builder = "nixpacks"
  buildCommand = "cd frontend && npm install && npm run build"
  
  [build.nixpacksPlan]
  [build.nixpacksPlan.phases.setup]
  nixPkgs = ["nodejs_20", "yarn"]
  
  [build.nixpacksPlan.phases.install]
  cmds = ["cd frontend && npm install"]
  
  [build.nixpacksPlan.phases.build]
  cmds = ["cd frontend && npm run build"]

[deploy]
  startCommand = "nginx -g 'daemon off;'"
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3

# Environment variables
[environments]
  [environments.production]
    NODE_ENV = "production"
    VITE_API_URL = "https://paxform-assessment-url.railway.app"
    PORT = 80
    
    # Database configuration
    DB_CONNECTION = "mysql"
    DB_HOST = "${RAILWAY_MYSQLHOST}"
    DB_PORT = "${RAILWAY_MYSQLPORT}"
    DB_DATABASE = "${RAILWAY_MYSQLDATABASE}"
    DB_USERNAME = "${RAILWAY_MYSQLUSER}"
    DB_PASSWORD = "${RAILWAY_MYSQLPASSWORD}"
